### ISSUE TITLE
curl: (56) Recv failure: 连接被对方重设

### ISSUE THREAD

**Issue by Aphrodite-Love** [Byaidu/PDFMathTranslate#464]
## 问题描述

使用docker启动远程服务后，使用curl或者requests api调用出错：

> curl: (56) Recv failure: 连接被对方重设

## 测试文档

使用README中的命令：

`curl http://localhost:11008/v1/translate -F "file=@example.pdf" -F "data={\"lang_in\":\"en\",\"lang_out\":\"zh\",\"service\":\"google\",\"thread\":4}"`

保证文件存在且不为空。

docker-compose文件如下：

```
version: '3.8'

services:
  pdf2zh:
    image: byaidu/pdf2zh
    ports:
      - "7860:7860"
      - "11008:5000"
    restart: unless-stopped
    environment:
      - HF_ENDPOINT=https://hf-mirror.com
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0', '1' ]
              capabilities: [ gpu ]

```
