### ISSUE TITLE
行重影与格式错误

### ISSUE THREAD

**Issue by frankjoey2048** [Byaidu/PDFMathTranslate#933]
### Before you asking

- [x] I have searched the existing issues
- [x] I spend at least 5 minutes for thinking and preparing
- [x] I have thoroughly and completely read the wiki.
- [x] I have carefully checked the issue, and it is unrelated to the network environment.

### Environment

- pdf2zh 2.0 preview（sha256:0d12e6fa8504d9754428286e61db5dfba46af82070ef8851389dca237c569dbc）

![Image](https://github.com/user-attachments/assets/5f4ca2ac-2f72-4e13-96c6-17133383cec7)

here is my docker-compose.yml:
```yaml
version: '3'
services:
  pdf2zh:
    image: ghcr.io/awwaawwa/pdfmathtranslate:dev
    ports:
      - "12345:7860"
    environment:
      - PDF2ZH_TRANSLATE_TABLE_TEXT=false
    command: ["pdf2zh", "--gui", "--openai-base-url", "https://api.gpt.ge/v1", "--openai-api-key", "sk-vROlxwnoGo0G0xvA4eFa3e6587D141D4B322A0B06fB50d02", "--openai-model", "gpt-4.1-nano", "--qps", "8"]

```
### How to install pdf2zh

docker

### Describe the bug

存在重影：

![Image](https://github.com/user-attachments/assets/6c6cf842-317f-4b60-a72e-9f79450397fb)

翻译格式错误：

![Image](https://github.com/user-attachments/assets/bb35a7a6-f273-4ac9-bb3e-463682c28fdf)

还有一个不算bug，algorithm这种也翻译，即使翻译这种格式也不对：

![Image](https://github.com/user-attachments/assets/9e55f85c-13ee-42fa-a292-ca9816bbcf8e)

### To Reproduce

1. select 
https://proceedings.neurips.cc/paper_files/paper/2024/file/1e5cff01121223de917a84a242de30a5-Paper-Conference.pdf

2. see errors
[NeurIPS-2024-ordered-momentum-for-asynchronous-sgd-Paper-Conference.zh-CN.dual.pdf](https://github.com/user-attachments/files/20223339/NeurIPS-2024-ordered-momentum-for-asynchronous-sgd-Paper-Conference.zh-CN.dual.pdf)

### Expected behavior

我希望可以纠正pdf翻译重影和格式错误的问题，以及改善计算机领域算法显示的问题

### Relevant log output

```Text

```

### Origin PDF file

[NeurIPS-2024-ordered-momentum-for-asynchronous-sgd-Paper-Conference.pdf](https://github.com/user-attachments/files/20223358/NeurIPS-2024-ordered-momentum-for-asynchronous-sgd-Paper-Conference.pdf)
